FeScore = int(input("Score of Foundation English : "))
GbScore = int(input("Score of General Business : "))
IcScore = int(input("Score of Introduction to Computer Systems : "))
CScore = int(input("Score of Computer Programming : "))

print("--- Your Score ---")
print("Foundation English :", FeScore)
print("General Business :", GbScore)
print("Introduction to Computer Systems :", IcScore)
print("Computer Programming :", CScore)